label sayori_exclusive4:
    $ sayori_hearttoheart = True
    stop music fadeout 2.0
    scene bg house
    with wipeleft_scene
    "I head to Sayori's house. It's a little early to start on the project, but I might as well check up on her."
    "Rather than asking, I simply text her \"I'm coming over\", much like we've done in the past."
    "Once I reach Sayori's house, I knock on the door before entering it myself."
    "Again, we used to play so often that we've made it a habit of simply entering each other's houses like we were family."
    scene black with wipeleft
    "The house is quiet."
    "Sayori isn't anywhere on the first floor, so I assume she's up in her room."
    "It's already strange of her not to run down and greet me."
    "I head up to her bedroom, where I finally find her."
    scene bg sayori_bedroom with wipeleft
    mc "Sayori?"
    play music t10
    show sayori 1ba zorder 2 at t11
    s "Hi [player]~"
    show sayori 1by
    "I sit down in her room."
    "Sayori forces a smile, but it's easy to tell that she's different."
    "There's a minute of silence between us."
    s "You haven't come over like this in a long time, have you?"
    mc "Ah... I guess you're right."
    mc "It has been a long time."
    mc "Not much has really changed, has it?"
    "Sayori's room is as messy as it's always been."
    "I also recognize the same stuffed animals and wall decorations that she's had for years now."
    s 2bl "Ehehe~"
    s "If you came over more often, it wouldn't be such a mess."
    mc "That's because I end up cleaning it for you..."
    "There's an awkward silence."
    show sayori 1bk
    "Sayori stares in a random direction."
    "Everything about her behavior is really uncharacteristic."
    "I finally get to the point."
    mc "I just...wanted to see how you were doing."
    mc "After you left."
    mc "I know something's wrong, so don't try to dodge."
    mc "I know you too well."
    mc "So..."
    "Sayori smiles, shaking her head."
    s 1bd "That's no good, [player]."
    mc "What?"
    s "Why can't it just be like it's always been?"
    s 1by "This is all my fault."
    s "If I didn't get so weak and accidentally express my feelings..."
    s 1bk "If I didn't make that stupid mistake..."
    s "Then you wouldn't have been worried about me at all."
    s "You wouldn't have come here."
    s 1bd "You wouldn't have even been thinking about me right now."
    s "But this...is just my punishment, isn't it?"
    s "I'm getting punished for being so selfish."
    s "I think that's why the world decided to have you come over today."
    s "It just wants to torture me."
    mc "Sayori!"
    show sayori 4bb
    "I grab Sayori by the shoulders."
    mc "What on Earth are you saying?"
    mc "Are you listening to yourself right now?"
    mc "I know something happened to you."
    mc "There's no other explanation for you to be like this."
    mc "So tell me, already...!"
    mc "Until I know, I won't be able to stop thinking about it!"
    s 4bl "Ah..."
    s "Ahaha..."
    "Sayori gives me an empty smile."
    s 4by "You really put me in a trap, [player]."
    s "But..."
    s 1ba "You're wrong."
    s "Nothing happened to me."
    s "I've always been like this."
    s "You're just seeing it for the first time."
    mc "Seeing what?"
    mc "What are you talking about, Sayori?"
    "Sayori sighs."
    s 1ba "You're really just going to make me say it, aren't you, [player]?"
    s "I guess I have no choice this time."
    s 1bc "The thing is..."
    s "I've had really bad depression my whole life."
    s 1bb "Did you know that?"
    s "Why do you think I'm late to school every day?"
    s "Because most days, I can't even find a reason to get out of bed."
    s 1by "What reason is there to do anything when I fully know how worthless I am?"
    s "Why go to school?"
    s "Why eat?"
    s "Why make friends?"
    s "Why make other people put their energy and caring to waste by having them spend it on me?"
    s "That's what it feels like."
    s "And that's why I just want to make everyone happy..."
    s "Without anyone worrying about me."
    mc "Wh-...what?"
    "I'm in shock."
    "I can't even figure out how to respond."
    "How is it possible that Sayori kept this from me the entire time that I've known her?"
    "Did she really want so badly for me to just not think about her?"
    mc "...Why, Sayori?"
    s 1bg "What?"
    mc "Why is it that you've never told me about this?"
    mc "It almost feels like I've been betrayed as your close friend."
    mc "Because if I knew, I would have done everything I could to support you!"
    mc "Even if there's only so much that I could do..."
    mc "I would have tried a little bit harder to make every day a little better for you."
    mc "That's why I'm your friend!"
    mc "All you had to do was tell me!"
    s 1bk "You don't understand at all, [player]."
    s "Why do you think I didn't tell you?"
    s 1bd "Because if I told you, then you would have to waste effort caring about me instead of doing important things."
    s "I don't want to be cared about."
    s "It's bittersweet, when people try to care about me."
    s 1ba "It feels nice sometimes."
    s "But it makes me feel even worse in the longrun."
    s 4ba "That's why I wanted so badly for you to make friends with everyone else..."
    s "Helping everyone be happy together is the best thing for me."
    s 1bb "But then, I discovered something else, too."
    s "Seeing you make friends and get closer with everyone in the club..."
    s 1bk "It made me realize you don't really need me anymore."
    s "So, that's why."
    s "That's why I decided the world just wants to torture me."
    s 1by "Every path leads to nothing but hurt."
    s "I can't even get satisfaction from helping others."
    mc "You're right that I don't understand..."
    mc "But I don't need to understand."
    mc "Whatever it takes for me to help you stop hurting..."
    mc "That's what I'll do."
    s 1bd "No, [player]."
    s "There's nothing."
    s "Nothing at all."
    s "The only thing that could have helped is if everything could be like it always was."
    s 1bk "But I was selfish."
    s "I finally showed you what a horrible person I am."
    "Tears streak down Sayori's face."
    s 1bv "I made you join the literature club because I was selfish."
    s "And I was punished by my heart hurting in a way that I couldn't understand."
    s "And now you came here and I made you hurt, too."
    s 1bt "I'm just weak and selfish."
    s "That's all I am."
    s "And that's why I'm going to accept these punishments."
    s 1bv "Because I deserve every last one."
    "Without thinking, I once again grab Sayori's shoulders."
    "This time, I pull her into a tight embrace."
    scene black with dissolve_cg
    s "[player]..."
    mc "Sayori."
    mc "I don't care if you feel selfish."
    mc "I'm really happy that you convinced me to join the club."
    mc "Seeing you every day makes it worthwhile enough."
    mc "If I make friends with everyone else, then that's just a bonus."
    mc "But please never underestimate how much I care about you."
    mc "I wouldn't have it any other way."
    s "[player]..."
    "Sayori isn't hugging me back."
    "Despite my arms being wrapped around her, Sayori's arms remain at her sides."
    "She starts sobbing next to my ear."
    s "No..."
    s "Don't do this...to me..."
    s "Please don't do this..."
    s "[player]..."
    s "I..."
    "Sayori barely manages to speak between her sobs."
    "I don't know if I'm doing the right thing."
    "But all I want is for her to know that I care."
    mc "If you have it in you to call yourself selfish, then you have to let me be selfish too."
    mc "No matter what it takes, I'll figure out what needs to change."
    mc "I'll make these feelings go away."
    mc "And if there's anything that you need me to do..."
    mc "Then you'd better tell me."
    mc "I'll get mad if you don't."
    s "I...don't know..."
    s "I don't know..."
    s "I don't know."
    "Gently, Sayori finally puts her arms around me in return."
    s "I don't know anything."
    s "It's all really scary..."
    s "I don't understand any of my feelings, [player]..."
    s "The only time I'm not feeling nothing is when I'm feeling pain."
    scene bg sayori_bedroom
    show sayori 1bv zorder 2 at i11
    with dissolve_cg
    "Sayori lets me go."
    "As she does so, I let her go as well."
    mc "The festival is on monday."
    s 1bk "Yeah..."
    mc "It's going to be fun, right?"
    s "Yeah."
    mc "How would you like for me to spend it all with you?"
    s 1bh "U-Um..."
    s "Ah--"
    mc "It's what I want."
    mc "I promise."
    s 1bk "I..."
    s "I think that would be nice, then..."
    mc "Yeah."
    "Sayori wipes her eyes."
    mc "We're going to do this project, alright?"
    s "Okay..."
    mc "And it's going to be the best project ever."
    "Sayori sniffs."
    s 4ba "Can you help me with it?"
    s "Not online, I mean."
    mc "I will."
    mc "I look forward to it."
    scene bg residential_day with wipeleft_scene
    "I say goodbye to Sayori and exit her house."
    "On the way home, I find myself still feeling uneasy."
    "I feel like I need to make the most of this weekend to connect with her."
    "To show her that she's not worthless."
    "She means a lot to me, and the Literature Club."
    "I hope she's okay."
    return
        