label natsuki_exclusive4:
    scene bg kitchen with wipeleft_scene
    "It's Sunday afternoon, and I'm suprisingly anxious about the festival."
    "It's just a stupid festival, but I'm kind of embarassed about what happened yesterday."
    "Suddenly, I hear the doorbell ring."
    "Who could that be?"
    "I walk up to open the front door."
    mc "Hello--?"
    "Someone is standing on my doorstep."
    "It's Natsuki."
    "She's crying."
    show natsuki 12f at t11
    play music t10
    "She quickly comes inside and closes the door behind her. I hear her breathing strangely."
    "After a moment facing the door, she turns around, and I get a look at her."
    "She looks terrible. Her clothes are disheveled, and her hair is unkempt, falling in front of her face."
    "She also has a black eye."
    "She's looks at me with tears streaming down her face."
    mc "W-What happened?"
    "She opens her mouth to speak, but hesitates."
    mc "Natsuki, who did this to you?!"
    "She shakes her head."
    mc "Natsuki..."
    n "[player]..."
    n 12i "I...I can't."
    "I grab her shoulders."
    mc "Natsuki, I can't help you if I don't know what's wrong. This is serious. What happened? Who did this to you?"
    "She wipes away a tear, sniffs, and looks down."
    n 12f "I've never..."
    n "I've never told anyone..."
    mc "Told anyone what?"
    n 12i "This isn't the first time..."
    mc "For what? Who did this to you?"
    "Natsuki still hesitates..."
    "I open my mouth, before I can say anything, she finally answers..."
    n 12f "My dad."
    mc "Oh."
    "I look away for a moment."
    "I was not expecting this."
    "I need to be careful what I say."
    "She sniffs again."
    "I lower my voice. I haven't started this on a good note."
    mc "Okay. Okay."
    mc "Come on."
    "I lead her over to the couch and sit down with her."
    "Her hair falls in front of her face."
    "I gently pull it back behind her ear."
    mc "Tell me what happened."
    "Her eyes are still full of tears, and she doesn't look me in the face."
    "Her feet fidget nervously."
    n 12h "He found out."
    mc "About what?"
    "She lets out a breath."
    "This must be hard for her."
    n 12f "About me texting you."
    "Her texting me?"
    mc "Why does he care about th--"
    "She suddenly stands up, throwing her hands up and yelling,"
    n 1p "Because he's a fucking asshole! He's a fucking deadbeat with no hope in his own life so he takes it out on me!"
    "Her lips quivers and her breath hitches."
    "I see her body is shaking slightly."
    "I have no idea how to respond."
    "She looks angry and desperate at the same time."
    "She takes a deep breath."
    n 12c "I-I dont know how to live with this anymore. I can't. I can't go on with this."
    mc "Natsuki--"
    "She glares at me."
    n 1p "No, [player], you don't understand."
    n "Do you know why I'm smaller than other girls my age?" 
    "What?"
    mc "I-I don't--"
    n "It's because I'm luck if I eat one meal a day."
    n "It's because if I'm at home, the only way to survive is to stay out of sight."
    n "It's because even if I'm at school, I can't afford to buy lunch."
    n "It's because every time I have to go home, I consider just walking away."
    n "I'd rather live on the streets than with him."
    "I can't meet her gaze."
    n 1r "I never get a break from him." 
    n "He doesn't let me leave the house except for school"
    n "You see what he did when he found out I was texting a boy."
    "She points to her black eye."
    "I'm too afraid to speak."
    "I had no idea..."
    "She had mentioned her father before, but I didn't think anything of it."
    "At most I thought he was just strict."
    "I couldn't imagine..."
    n 12f "I just..."
    "Her voice breaks."
    "I look up, and her eyes are squeezed shut, new tears streaking down her face."
    "I don't know what to do."
    "I can't find the words to comfort her."
    "There's a silence between us, only broken by her whimpers."
    n "There's nowhere to hide from him. There's no where to run from him. School is the only place I get a break."
    n "The only reason I'm able to be here now is because he's out."
    "She opens her eyes, looking right at me."
    n 12h "I have no one else to turn to, [player]."
    n "I'm..."
    "She pauses, wiping her nose."
    n 1m "I'm scared, [player]."
    n "Of what he'll do to me next."
    n "What the hell do I do?"
    "I can't meet her gaze. I look down."
    "She sits down next to me, putting her head in her hands."
    n 12f "What the hell do I do..."

    menu:
        "Stand up to him.":
            call natsuki_exclusive41
            
        "Go to an adult.":
            call natsuki_exclusive42

    return
    
label natsuki_exclusive41:
    $ natsuki_choice = 1
    mc "Stand up to him."
    "Natsuki looks up."
    n 12i "What? Are you crazy?"
    mc "You can't keep taking this from him. Stand up to him, threaten to call the cops. Make him back down."
    n 12h "He'll kill me!"
    mc "No he won't."
    n 1e "You don't know him. He doesn't think about consequences."
    mc "Natsuki, if he does anything, you can go to the police. He'll face life. Do you think he won't take that into account?"
    n 4q "Well..."
    "She looks away, doubt creeping into her voice."
    "There's a moment a quiet while she considers it."
    n 1m "B-But it's just me. He'll never listen to me."
    mc "It won't be just you. You already told me."
    "She looks at me."
    "She looks slightly more hopeful."
    n 1k "R-Really?"
    "I nod."
    mc "We're going to get through this."
    show natsuki 12d
    "She looks down, closing her eyes."
    n "I want to believe that."
    n "I want to believe..."
    "She looks so small and vunerable..."
    "I don't know what to do..."
    "I want to comfort her..."
    "Hoping she doesn't yell at me, I put my arm around her."
    "I feel her body tense, but she doesn't push me off."
    "After a moment, she leans into me, letting out a sob."
    mc "We're going to get through this."
    "I'm not sure what else to say."
    "I hope I can live up to that promise."
    "We stay like that for a long time."
    "After a while, I hear her let out a breath."
    "Her shoulders don't look so slumped anymore."
    "She wipes her nose."
    n 1k "Thanks, [player]."
    n "I needed that."
    "I smile."
    mc "No problem, Natsuki."
    "We sit for a while longer."
    "I feel her shifting. She's going to leave."
    "I want to say something, but I don't know what."
    "Eventually, she gets up and starts towards the door."
    "She opens the door, but before she leaves, she turns to me,"
    n "See you tomorrow, [player]."
    mc "See you tomorrow, Natsuki."
    "The sound of the door closing almost hurts."
    "Despite what I said..."
    "I'm scared for her too."
    return

label natsuki_exclusive42:
    $ natsuki_choice = 2
    mc "Go to an adult."
    "Her voice is muffled from behind her hands,"
    n "That won't help."
    mc "Natsuki, this is serious. You need to contact someone, like the school counseler."
    mc "They could help you."
    "Natsuki looks up, doubtful."
    "Her cheeks are shiny with tears."
    n 12h "I don't know, [player], what if he finds out?"
    "The way she said that..."
    "It hits me how scared she is."
    "Her father feels like a shadow hanging over us."
    "Like there's a presence watching us."
    mc "It doesn't matter, you can't keep allowing this."
    mc "You need help, from someone with authority."
    n 12i "I've been dealing with this for so long..."
    n "I'm almost scared to..."
    "She shuts her eyes."
    n 12c "It's stupid..."
    n "It's almost more scary to...change...."
    "Her father has instilled such terror in her..."
    "She's lived in fear for so long..."
    "That she's even more scared of changing it."
    mc "Natsuki, you have to."
    n 12f "I know."
    n "I'm just...scared..."
    "She looks so small and vunerable..."
    "I don't know what to do..."
    "I want to comfort her..."
    "Hoping she doesn't yell at me, I put my arm around her."
    "I feel her body tense, but she doesn't push me off."
    "After a moment, she leans into me, letting out a sob."
    "We stay like that for a long time."
    "I can't help but hope it never ends."
    "She's so deperate for protection..."
    "I would fight the whole world for her."
    "I feel her shifting. She's going to leave."
    "I want to say something, but I don't know what."
    n 1m "T-thanks, [player]."
    n "I needed that."
    "I give her a smile."
    "What else can I do?"
    mc "No problem, Natsuki."
    "She gets up and heads towards the door."
    "She opens it, but before she leaves, she turns to me,"
    n 1k "See you tomorrow, [player]."
    mc "See you tomorrow, Natsuki."    
    "The sound of the door closing almost hurts."
    "Despite what I said..."
    "I'm scared for her too."
    return
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
