label ch4_exclusive_yuri:
    play music t6 fadeout 2.0
    scene bg house with wipeleft_scene
    "It's sunday."
    "I still can't believe Yuri's coming over."
    "My phone goes off. She's outside."
    "I quickly open the door, trying to contain my jitters."
    show yuri 2bq zorder 2 at t11
    y "Hey, [player]"
    mc "You're a little early..."
    mc "I see you brought a lot of stuff with you."
    y 1ba "That's right."
    y "And did you manage to find everything I asked you to buy as well?"
    mc "Yeah, pretty much."
    mc "At least, I hope I got everything right."
    y "I'm sure it will be fine."
    scene bg bedroom with wipeleft
    "I take Yuri to my room."
    "The first thing she does is glance around curiously, which makes me feel anxious."
    show yuri 2bm zorder 2 at t11
    y "It's so clean..."
    mc "Ahaha..."
    mc "I cleaned it before you came over, so..."
    y 2ba "That's very considerate of you to do."
    mc "Ah, no..."
    mc "I would be really embarrassed for my room to be a mess while you were here."
    y 1ba "Hmm..."
    y "Well, I do enjoy cleaning..."
    y "I would have gladly helped you clean."
    mc "Ah--"
    mc "That would be even more embarrassing!"
    show yuri 1be
    mc "Wait, don't look in there--!"
    "I snatch Yuri's wrist, which was in the process of opening a desk drawer of mine."
    y 3bn "A-Ah..."
    y "I'm sorry...!"
    y 4bb "I wasn't thinking for some reason..."
    y "I was just spacing out!"
    mc "It's fine, it's fine..."
    "I let go of Yuri's wrist."
    show yuri 1bl
    "She puts both of her hands firmly in her lap, as if making sure she's keeping track of them."
    mc "So, um..."
    mc "Should we...get started?"
    y 2bu "Ah..."
    y "Yes..."
    y 2bf "Um, I have a few things planned that you can help with..."
    y "Decorations and other atmospheric enhancements."
    mc "Atmospheric enhancements...?"
    y 1ba "You know..."
    y "Mood lighting, aromatherapy candles..."
    mc "Oh, wow."
    mc "I didn't know you planned on taking it that far."
    y 1bc "Of course."
    y "I want to help take our guests to a faraway place."
    y 1ba "Although many will stop by just out of curiosity..."
    y 1bj "And for...cupcakes, I guess..."
    y 1ba "I'm determined to provide an experience that will leave them wanting more."
    mc "That's great."
    mc "It's easy to forget that you're a pretty intense person."
    y 1bt "Ah--"
    y 2bt "Intense...?"
    mc "I guess that's the best way to put it."
    y "Is that...a bad thing?"
    mc "No, not at all."
    mc "It's something that I like about you, actually."
    y 3bu "I-Is that so...?"
    y "That makes me feel relieved..."
    y "And kind of happy..."
    mc "Yeah, no need to be so anxious."
    mc "You can relax a little."
    y 3bl "Relax..."
    y 1bf "I brought some things for relaxation."
    y "I was going to use them during the poetry event..."
    mc "Oh yeah? Like what?"
    y "Let's see..."
    "Yuri rummages through her bag."
    "She pulls out a few candles and a wooden cylinder-shaped object."
    y "I did some shopping on the way here, so I happen to have these in my bag."
    y "I planned to cover the windows in black paper and use the candles to light the room."
    y 1ba "I think that would be amazing, don't you?"
    mc "Yeah, that would be really neat."
    mc "What's that wooden thing, though?"
    y 1bf "Oh, this?"
    y "It's a diffuser for essential oils."
    y "How familiar are you with aromatherapy?"
    mc "Not familiar at all..."
    y 1ba "Ah, is that so?"
    y "It's one of my favorite contributors to a positive atmosphere."
    y "Depending on the oils or herbs you choose, you can change the mood of the air itself."
    y "You can even feel it permeate through your body."
    y 3bm "Relaxation, positive energy, romance, reflection..."
    y "It's almost like magic."
    show yuri 3ba
    "Yuri takes the cylinder and pushes a switch on the bottom."
    "In just a moment, a thin ray of vapor begins to spout through a small hole on the top."
    mc "Wow, that smells wonderful."
    mc "What kind of mood is that one for?"
    y 1ba "This is a Jasmine essential oil."
    y "It smells a little sweet and flowery, right?"
    mc "Yeah, that's a good way to describe it."
    y 1bb "I chose Jasmine for the event because it provides more than relaxation."
    y "Jasmine enhances your emotions and helps you feel them flow through your body."
    y 1bu "You feel warmer, and your heart pounds more heavily."
    y 1ba "Don't you think that will be perfect for sharing our poems?"
    mc "It does sound suitable..."
    mc "But you seem to know a lot about this, so I'll trust your opinion with anything."
    show yuri 1bc
    "Yuri smiles gently, clearly enjoying herself."
    "She again reaches into her bag and pulls out several spools of thin ribbon."
    show yuri 1ba
    mc "What are those for?"
    y 1bf "Well..."
    y "Did you purchase the origami paper I asked you to get?"
    mc "Yeah, I have it over here..."
    y "We won't be using the paper for folding origami."
    y "What I'd like to do is write a different word on each paper."
    y "We'll need about a hundred of them."
    mc "Oh yeah?"
    mc "What will those be used for?"
    y 2bf "Well, I'm going to cut pieces of ribbon to hang from the doorway of the classroom."
    y "Then, we can fasten the paper onto the ribbons to create a doorway curtain."
    y 2bm "Wouldn't that be beautiful?"
    y "It would also catch the eye of those passing by the room..."
    y 2ba "It may attract some to peek inside."
    mc "That's really creative!"
    mc "I had no idea you'd be so good at this, Yuri."
    y 4ba "Is...that so?"
    y "Well, I suppose I do get a little intense...as you'd put it."
    y 3bu "Uhuhu."
    "Yuri giggles with red cheeks."
    "Is it just me, or is she more relaxed when it's just the two of us?"
    "Or maybe it's the excitement she feels from sharing something that she enjoys."
    y 1ba "Here's a marker, [player]."
    y "You can write any characters you want."
    y "I'll help you once I finish cutting the ribbons."
    mc "Ah, alright."
    "Sitting on the floor together, the two of us get to work."
    "I carefully draw a different character on each paper, doing my best to manage my bad handwriting."
    "Yuri unravels a long strand of red ribbon to her desired length."
    "Then, she reaches into her bag once more and pulls out a pocket knife."
    mc "Eh...?"
    "The knife is strangely beautiful."
    "The silver handle has an intricate pattern of waves etched into it."
    "The blade itself is gently tinted blue."
    mc "That's no ordinary pocket knife..."
    mc "It looks really fancy."
    y 4bb "A-Ah..."
    y "Well..."
    "Embarrassed, Yuri looks away."
    mc "What is it?"
    y "You're going to think it's weird..."
    mc "Yuri, whatever it is, I have no reason to judge."
    mc "To each their own, you know?"
    y "If you promise you won't be weirded out..."
    mc "Yeah, I promise."
    y 2bi "Alright..."
    y "The thing is, I'm kind of into knives..."
    y "They're just...so pretty..."
    y 2bv "I-I can't help it!"
    y "I don't know what it is..."
    y "The combination of craftsmanship and feeling of danger, maybe..."
    y 4bb "Uu, what am I saying...?"
    y "Please don't think I'm weird for this..."
    mc "Ahaha."
    y "You're laughing at me..."
    mc "No, I'm not laughing at you."
    mc "It's just funny how nervous you got about sharing."
    mc "It's...well, it's an interesting thing to be into, I guess."
    mc "But I think it kind of suits you."
    y 2bt "Suits me...?"
    mc "Yeah... It's kind of intense. Ahaha."
    mc "Besides, it's a really cool-looking knife, I can't deny that."
    y 2bu "It is, isn't it...?"
    "Yuri relaxes her expression once again."
    y 1ba "Would you like to hold it?"
    mc "Sure, I'll check it out."
    "Yuri carefully hands me the knife, with the handle facing me."
    "I take it and turn it around in my hands."
    "It feels heavy, and extremely solid."
    "Where do you even get a knife like this...?"
    "Curious of its sharpness, I feel the point of the knife with my index finger."
    mc "Ow--!"
    y 3bn "[player]--!!"
    y "Why did you do that?!"
    mc "I didn't expect it to be that sharp...!"
    mc "I barely touched it at all."
    y "I-It's my fault!"
    y 3bo "I should have warned you..."
    y "This knife is extremely sharp..."
    y "It can cut through skin like it's paper."
    y 2bv "Oh no..."
    "A small drop of blood trickles down the side of my finger."
    "Yuri takes my hand and gives the wound a closer look."
    y 2bt "Ah..."
    "She stares at it and noticeably fidgets."
    mc "If you're squeamish, I'll go wash it off now--"
    mc "A-Ah!"
    "Without warning, Yuri puts my finger in her mouth and licks the wound."
    "I feel her tongue curl around my finger."
    "Startled, I instinctively pull my hand back."
    y "O-Oh..."
    y 3bo "P-Please forgive me!"
    y "I wasn't thinking!"
    y 4bc "I..."
    "Yuri lowers her head, her face burning up."
    mc "Yuri..."
    y "That's the most embarrassing thing I've ever done..."
    y "How could I do something like that??"
    y "I'm sorry, I'm sorry..."
    mc "Ah..."
    "Sure, it was a little weird, and it took me by surprise..."
    "But I guess she was just trying to help, right...?"
    mc "Yuri, I think you're overreacting a little..."
    y "Uuuh..."
    "She doesn't lift her head."
    "What if she doesn't recover from this for the rest of the afternoon?"
    mc "Alright, you know what..."
    "This might be a stupid thing to do, but I do it anyway."
    "I take Yuri's hand and lick her index finger in return."
    show yuri 3bn at h11
    y "[player]--!!"
    y "D-Did you really just do that?"
    mc "N-Now we're even..."
    y 3bv "..."
    "Yuri just looks at me like I did something wrong."
    mc "Ahaha..."
    mc "I knew that would be a bad idea..."
    "If not for the sweet aroma of the Jasmine oil, the air would be extremely heavy right now."
    y 1bu "You're so weird, [player]."
    "Yuri giggles shyly."
    mc "Eh...?"
    "Yuri calling {i}me{/i} weird?"
    "I have no response to that..."
    y 1bf "Where do you keep your bandages?"
    mc "Ah..."
    mc "I don't think I need one, actually."
    mc "It was a tiny cut."
    mc "Look, it already stopped bleeding."
    y 1ba "I see..."
    y "That's relieving."
    "The tension is quickly lifted."
    "We each resume our respective activities."
    "I watch Yuri's knife cut through the ribbon like it's nothing but air."
    "Meanwhile, I continue to make progress on the paper."

    scene bg bedroom with wipeleft_scene
    "After we finish attaching the paper to the ribbons, we lay them all out side by side."
    "It looks better than I expected and will be very effective as a door curtain."
    mc "It looks great."
    mc "Good thinking coming up with this, Yuri."
    show yuri 1bq zorder 2 at t11
    y "Ah, thanks..."
    y "It's just something I saw online, really."
    y 1ba "Are you ready to move onto the next task?"
    mc "Yeah, let's do it."
    mc "What do you have in mind?"
    y "I'd like to create a banner."
    y "That's why I asked you to buy the paint tablets."
    mc "Ah, that's right."
    "One of the items Yuri had asked me to buy was a kit of watercolor paint tablets."
    y 1bf "We'll need about six cups of water to put each of the tablets in."
    y "While you're doing that, where's your bathroom?"
    "It catches me a little off guard, but I tell her where it is and go to get the cups."

    scene bg bedroom with wipeleft_scene
    "Taking Yuri's advice, I decide to use small plastic bathroom cups rather than full-sized glasses."
    "I put them on a plate to catch any paint that drips, then bring it back into my room."
    "I start working, when I hear the bathroom door open. I look up to see Yuri coming out."
    "She seems to be fiddling with her sleeve. She must be as nervous as I am."
    mc "Yuri?"
    show yuri 1bd zorder 2 at t11
    y "Yes?"
    mc "Ah, nothing..."
    mc "Your face is a little red."
    mc "Is it too hot in here, or anything?"
    y 3bq "Ah--"
    y "No, not at all!"
    y "There's nothing wrong, so..."
    y "Let's mix the paint."
    "Yuri hurriedly dismisses me and takes it upon herself to unwrap the tablets, dropping them into the cups."
    y 1ba "So..."
    y "I thought we would do something simple that would look very nice."
    y "I'd like to paint a gradient across the banner..."
    y "Starting with the colors for a sunrise, then daytime, then sunset and nighttime."
    y "Once it dries, I'll write an inspirational quote across the banner."
    y "We can hang it on the wall behind the podium at the front of the classroom."
    mc "Ah, neat."
    mc "What are you going to write?"
    y 2bm "Well..."
    y "...It will be more fun to surprise you."
    "Yuri smiles at me."
    mc "If you say so..."
    show yuri zorder 1 at thide
    hide yuri
    "After rolling out the banner, Yuri and I kneel on opposite sides so we don't get in the way of each other."
    "Yuri uses a brush and adds a few dots of different colors across the banner to serve as a color guide when we paint."
    mc "This kind of reminds me of elementary school..."
    "Painting on a banner with watercolors feels a lot like the art class projects we had back then."
    "It's relaxing."
    show yuri 2bt zorder 2 at t11
    y "Ah..."
    y "I'm sorry if this feels too childish...!"
    mc "No, I didn't mean that at all."
    mc "It's kind of fun, you know?"
    y 1bs "...Yeah."
    y "It is fun."
    y "I'm glad you feel that way, too."
    "Yuri stops painting for a moment, thinking to herself."
    y 2bl "For me..."
    y "I don't need to go out and do crazy things to have fun."
    y "In fact, I usually don't even want to."
    y 2bf "I just like when I can spend time with one other person..."
    y "Even if it's something simple, like reading - it doesn't even matter if we don't talk much."
    y 2ba "Just having a friend next to me makes things feel a little bit nicer."
    y "I think that's all it takes for me to be happy."
    mc "Is that so...?"
    "Even if Yuri and I are quite different, I can understand where she's coming from."
    "I feel that way about things like anime and games, where simply sharing the experience with someone can make me happy."
    mc "I think I feel the same way."
    "Yuri smiles gently."
    y 1bm "I knew you'd understand..."
    "Yuri leans over the banner to grab an unused paintbrush."
    "But I move at the same time, causing my head to bump into hers."
    y 3bn "Kya--!"
    mc "S-Sorry!"
    "Yuri reels back, and I quickly lift my hands in surprise."
    mc "Are you hurt?"
    y 2bv "N-No, I'm not hurt."
    y "It just startled me...that's all."
    y "Sorry, I should have asked you to get it for me..."
    mc "It's not your fault."
    mc "Ah, your face..."
    "There are droplets of paint on Yuri's face and neck."
    y 2bt "Is there something on my face?"
    mc "Yeah, I accidentally got paint on you..."
    mc "Sorry, it's totally my fault!"
    mc "I'll get a towel right away."
    show yuri zorder 1 at thide
    hide yuri
    "I rush out and fetch a small towel, then I dampen it with hot water."
    "I return to my room and kneel back down in front of her."
    $ persistent.clear[5] = True
    scene y_cg3_base with dissolve_cg
    mc "Here..."
    "I pat down Yuri's face and neck with the towel."
    show y_cg3_exp1 at cgfade
    y "Ah--"
    mc "Is something wrong?"
    y "It's hot...I just didn't expect it."
    mc "Sorry..."
    mc "I didn't want to use cold water."
    "Having finished, I start to retract my hand."
    "But Yuri suddenly holds my wrist."
    hide y_cg3_exp1
    y "Wait--"
    mc "Eh?"
    show y_cg3_exp1 at cgfade
    y "Just...for a little longer."
    y "It feels really nice..."
    mc "Ah..."
    "I keep my hand still against Yuri's neck."
    hide y_cg3_exp1
    "She looks into my eyes."
    "It's an intense expression that I recognize from when she reads her books..."
    "Almost as if she's lost in a daze, enveloped by her own thoughts."
    "She breathes gently, half through slightly-parted lips."
    "What is happening...?"
    "Is it the aroma of the Jasmine oil giving me this dizzy feeling?"
    "Yuri's gentle fingers, wrapped around my wrist, send a tingling sensation through my arm."
    "And suddenly, her face seems to be much closer to mine than it was just a moment ago..."
    y "Ah..."
    "Yuri slowly pulls away."
    y "Sorry..."
    y "I've been feeling a little light-headed today."
    y "I didn't mean to space out..."
    mc "I-It's fine..."
    scene bedroom with dissolve_cg
    "The moment is over as soon as it began."
    "Yuri picks up her brush again."
    "But her movements seem clumsier, like she's unable to focus."
    "I remain silent, forced to ignore the event that just transpired."
    "I hesitantly retrieve my own brush and continue following Yuri's example."

    scene bedroom with wipeleft_scene
    mc "That should do it..."
    "I finish filling the night sky with white dots that looks like stars."
    "Looking at the banner as a whole, it's very pretty and natural-looking."
    show yuri 1ba zorder 2 at t11
    y "I think it came out better than I expected."
    y "I'm really happy with the results."
    mc "Yeah, me too."
    mc "Are you going to add the lettering now?"
    y 1bf "Ah, not yet..."
    y "It needs to dry first."
    mc "That's true, but won't that take a while?"
    y 2bh "Well..."
    y "Perhaps it would be best to leave it here, then have you bring it in the morning."
    y 2bf "I can do the lettering in the classroom before our event starts."
    y "Is that okay?"
    mc "That's totally fine."
    y 1ba "Wonderful."
    y "In that case..."
    y "I don't think there's anything more for us to do here."
    mc "You say that like you're glad it's over."
    y 4bc "What--that's not what I meant! I-I didn't--"
    "I laugh."
    mc "I'm only teasing you, Yuri."
    "I playfully hit her arm. Suddenly, she winces. My smile disappears."
    mc "Yuri? You okay? I didn't mean to hit you so hard..."
    y 3bo "N-no! It's not...It's not that..."
    "Wait a minute, is her sleeve red?"
    mc "What's this?"
    "I start pulling up her sleeve..."
    "She suddenly yanks her arm away from me."
    y 3bn "No!"
    "I stare at her. What's going on?"
    "She seems to realize how loud she yelled that."
    "She fidgets nervously."
    y 3bo "I-I'm sorry, I didn't mean to shout. It's just..."
    "She looks down and fidgets with her sleeve."
    "I saw her do that earlier."
    mc "Yuri..."
    "She looks up at me."
    "She looks terrified."
    mc "What's under your sleeve?"
    y "[player]..."
    mc "Tell me, Yuri."
    "She looks around nervously."
    y 4ba "I-I have to go..."
    mc "Yuri."
    mc "Show me your arm."
    "She squeezes her eyes shut..."
    stop music fadeout 2.0
    "...and slowly pulls up her sleeve."
    play music t10
    "It's covered in cuts, some of them still bleeding."
    mc "Oh my God..."
    y 3bo "I-I don't--"
    "I had no idea..."
    "I take a step forward."
    "She flinches away, but I slowly extend my hand to hold hers, pulling her back towards me."
    mc "Yuri..."
    "I look at her arm."
    "Some of the cuts have healed, others are in the process."
    "It's obvious she's been doing it for a long time."
    mc "Yuri...why?"
    "She looks down."
    "There's a tear rolling down her cheek."
    y 3bv "I can't help it. It just...it feels good."
    "I shake my head."
    mc "Yuri you can't keep doing this. You'll die."
    "She's still looking away."
    mc "Yuri!"
    "I grab her shoulder and shake her. She looks at me."
    show yuri 2bf
    mc "Do you understand? You could die if you keep doing this."
    "She looks down in shame."
    y 3bw "Oh, [player], I know."
    y "I just...it helps."
    y "I have to."
    mc "Yuri...do you understand how serious this is?"
    y "But they--"
    "She suddenly stops talking."
    show yuri 3bn
    "She looks terrified."
    mc "W-what? Who?"
    y 3bo "I can't--"
    mc "Yuri."
    mc "Who is 'they?'"
    y 4bc "[player]..."
    "She looks like she's about to run out the door."
    mc "Yuri. Talk to me."
    "She flinches."
    y "[player]...I..."
    y 3bv "I hear..."
    "Oh God."
    y "I hear things..."
    "My eyes close."
    "This is even worse than I could have ever imagined."
    y 3bw "I'm a monster..."
    "I open my eyes."
    mc "What?"
    mc "Yuri, no."
    y 3bv "I'm a freak."
    mc "Yuri, you're not a freak."
    y "[player], I..."
    y "I hear voices."
    y "That's why I do this to myself."
    y "They tell me to."
    mc "I don't care."
    y 2bf "W-what?"
    mc "I'm not going to run from you."
    mc "I'm not going to call you a freak."
    y "[player], don't--"
    mc "I want to help you."
    "Yuri takes a step back from me."
    y 3bv "No..."
    y "[player]..."
    y "Don't do this..."
    mc "Yuri, you need help."
    mc "You can't do this alone."
    y 4bb "I-...I can't--"
    mc "Yes you can, Yuri."
    mc "We can get through this."
    y 4bd "W-we?"
    "I offer my hand to her."
    mc "Together."
    "There's a moment of quiet."
    "She looks at my hand, hesitant."
    y 3bw "I...I just..."
    "She looks down."
    "There's a moment of silence."
    "I don't want to rush her."
    "I wait."
    "Slowly, she reaches out her hand to grasp mine."
    y 1be "T-together."
    "I see a tear sliding down her cheek."
    "I gently pull her into a hug."
    scene black with wipeleft
    "I can hear her quietly sobbing."
    mc "It's okay."
    mc "We're going to get through this."
    mc "You don't need to do this alone."
    "She doesn't respond, but she wipes her tears away."
    mc "You can count on me."
    "I hear her crying begin to fade."
    "We hold each other for what feels like forever."
    "Eventually, she pulls back from the hug."
    scene bg bedroom with wipeleft
    show yuri 2bj at t11
    "She wipes her nose."
    y 3bg "T-thanks [player]."
    y "I just..."
    y 4ba "I try to distance myself from people..."
    y "Because I don't want to trouble them with..."
    y "With my problems..."
    mc "It would be more troubling for me if you didn't trouble me with your troubles."
    y 3by "What?"
    mc "I--uh..."
    show yuri 3bd
    "She suddenly bursts out laughing."
    "I can't help but crack up myself."
    y 3bc "Oh my God."
    y 3bj "[player], you know..."
    y "Spending time with you..."
    y 3bb "It helps."
    "..."
    "Wow."
    mc "Well, I'm glad to be of service."
    show yuri 3bc
    "She laughs again."
    "I like that sound."
    y 2bu "Well..."
    y "I guess I'll see you at the festival."
    mc "Sounds good Yuri."
    mc "Take care, alright?"
    y 2ba "Alright..."
    scene black with wipeleft
    "She seems a lot better."
    "I'm glad to have helped."
    "I'll be sure to text her regularly."
    "She needs the support."    
    return
    